"""
Django settings for q_trivia project.

Generated by 'django-admin startproject' using Django 6.0.5.
Optimized for high-concurrency production transaction scaling.
"""

import os
from pathlib import Path
from dotenv import load_dotenv  # <-- Added for loading your environment configuration safely
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load the .env file from the project root next to manage.py
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-*78ns3ncl37x=t6ie)w!%&zd6^wg(gh0uyhhk1eq@d5(m@dx1q')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Custom Applications
    'quiz.apps.QuizConfig',
]

# Explicitly link custom transaction-hardened profile tracking layer
#AUTH_USER_MODEL = 'quiz.UserProfile'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'q_trivia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'q_trivia.wsgi.application'


# Database Configuration
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# NOTE FOR PRODUCTION ENGINES (PHASE 6 EXPECTATIONS):
# When hooking into PostgreSQL multiplexers like PgBouncer in transaction mode, 
# remember to explicitly configure your pooling dictionary to include:
# 'CONN_MAX_AGE': <short_reusable_seconds_integer>
# 'OPTIONS': {'DISABLE_SERVER_SIDE_CURSORS': True}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'  # Tuned explicitly to align localized pool windows with regional traffic baselines

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Scale-Ready Primary Key Configuration Rules
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Third-Party Integrations Pipeline Configurations ---

# Pull the API access credentials securely loaded out of the .env file
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_SUBACCOUNT_CODE = os.getenv('PAYSTACK_SUBACCOUNT_CODE')
PAYSTACK_BEARER = os.getenv('PAYSTACK_BEARER', 'subaccount')

# Celery Configuration Settings
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Or your specific Redis/RabbitMQ URL
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_TIMEZONE = 'Africa/Nairobi'  # Alignment tracking for East Africa Time (EAT) Clock

# --- CELERY BEAT PERIODIC SCHEDULER MATRIX ---
CELERY_BEAT_SCHEDULE = {
    'execute-tournament-pool-rotation-every-2-hours': {
        'task': 'quiz.tasks.run_management_command_rotation',
        'schedule': crontab(minute=0, hour='*/3'),  # Runs precisely at minute 0 of every 2nd hour (e.g., 12:00, 2:00, 4:00)
    },
}