# Generated by Django 6.0.6 on 2026-07-03 11:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackTransaction',
            fields=[
                ('paystack_reference', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('player_name', models.CharField(blank=True, help_text='Captured M-Pesa Name', max_length=150, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('access_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_token_used', models.BooleanField(db_index=True, default=False)),
                ('backend_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'quiz_paystack_transaction',
            },
        ),
        migrations.CreateModel(
            name='QuizPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(db_index=True)),
                ('total_entry_fees_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_prize_pool', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'quiz_pool',
                'indexes': [models.Index(fields=['is_active', 'start_time', 'end_time'], name='quiz_pool_perf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('grand_prize_pool__gte', Decimal('0.00'))), name='grand_prize_pool_cannot_be_negative')],
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, db_index=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_disqualified', models.BooleanField(db_index=True, default=False)),
                ('transaction_reference', models.OneToOneField(db_column='transaction_reference', on_delete=django.db.models.deletion.CASCADE, related_name='game_session', to='quiz.paystacktransaction')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_sessions', to='quiz.quizpool')),
            ],
            options={
                'db_table': 'quiz_game_session',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('choice_1', models.CharField(max_length=255)),
                ('choice_2', models.CharField(max_length=255)),
                ('choice_3', models.CharField(max_length=255)),
                ('choice_4', models.CharField(max_length=255)),
                ('correct_choice', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('LOCAL_FOOTBALL', 'Local Kenyan Football'), ('KENYAN_HISTORY', 'Kenyan History'), ('WORLD_FOOTBALL', 'World General Football')], db_index=True, max_length=50)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quizpool')),
            ],
            options={
                'db_table': 'quiz_question_bank',
                'constraints': [models.CheckConstraint(condition=models.Q(('correct_choice__gte', 1), ('correct_choice__lte', 4)), name='valid_choice_index_range')],
            },
        ),
    ]
