# Generated by Django 6.0.6 on 2026-07-08 10:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizpool_retained_company_earnings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenueAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(default='Administrative Platform Revenue', max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'quiz_platform_revenue',
            },
        ),
        migrations.AddField(
            model_name='quizpool',
            name='requires_manual_audit',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='quizpool',
            name='total_entries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='access_token',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='PayoutEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('SUCCESS', 'Payout Successfully Credited'), ('FAILED', 'Payout Execution Failed')], default='PENDING', max_length=15)),
                ('payout_reference', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_event', to='quiz.gamesession')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='quiz.quizpool')),
                ('transaction_receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_records', to='quiz.paystacktransaction')),
            ],
            options={
                'db_table': 'quiz_payout_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payout_status_date_idx')],
            },
        ),
    ]
