# Generated by Django 6.0.6 on 2026-07-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_platformrevenueaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystacktransaction',
            name='payout_status',
            field=models.CharField(choices=[('UNPROCESSED', 'Active Pool / Unprocessed'), ('PENDING', 'Pending Payout'), ('PAID', 'Paid Successfully'), ('FAILED', 'Payout Failed'), ('EVALUATED', 'Closed Pool / No Prize')], db_index=True, default='UNPROCESSED', help_text='Tracks clean handoffs across recurring 3-hour pools', max_length=20),
        ),
    ]
