# Generated by Django 6.0.6 on 2026-07-13 09:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_paystacktransaction_payout_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizUserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tickets_available', models.IntegerField(default=0)),
                ('total_games_played', models.PositiveIntegerField(default=0)),
                ('onboarding_staff_name', models.CharField(blank=True, max_length=150, null=True)),
                ('onboarding_staff_emp_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'quiz_user_profile',
            },
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='payout_status',
            field=models.CharField(choices=[('UNPROCESSED', 'Active Pool / Unprocessed'), ('PENDING', 'Pending Payout'), ('PAID', 'Paid Successfully'), ('FAILED', 'Payout Failed'), ('EVALUATED', 'Closed Pool / No Prize')], db_index=True, default='UNPROCESSED', max_length=20),
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='player_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(fields=('transaction_reference', 'pool'), name='unique_game_per_transaction_pool'),
        ),
        migrations.AddConstraint(
            model_name='quizuserprofile',
            constraint=models.CheckConstraint(condition=models.Q(('wallet_balance__gte', Decimal('0.00'))), name='wallet_balance_cannot_be_negative'),
        ),
        migrations.AddField(
            model_name='paystacktransaction',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='quiz.quizuserprofile'),
        ),
    ]
