# Generated by Django 6.0.7 on 2026-07-21 11:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_standbyquestion'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionbank',
            name='valid_choice_index_range',
        ),
        migrations.AddField(
            model_name='paystacktransaction',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paystacktransaction',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='quiz.quizpool'),
        ),
        migrations.AddField(
            model_name='paystacktransaction',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='paystacktransaction',
            name='time_taken',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='paystacktransaction',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='duration_seconds',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='paystacktransaction',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='category',
            field=models.CharField(choices=[('LOCAL_FOOTBALL', 'Local Kenyan Football'), ('KENYAN_HISTORY', 'Kenyan History'), ('WORLD_FOOTBALL', 'World General Football'), ('GENERAL', 'General Knowledge')], db_index=True, default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='correct_choice',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='standbyquestion',
            name='correct_choice',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
